platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do

    pod 'Hyphenate'

    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

    pod 'RedpacketAliAuthLib', '~> 1.1.4'

end

target 'ChatDemo-UI3.0-JDPay' do
    
    pod 'Hyphenate'
    
    pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
    
    pod 'RedpacketLib'

end
