platform :ios, '7.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do

pod 'Hyphenate_CN'

pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

pod 'RedpacketLib'

end
