platform :ios, '10.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseIM' do

    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'SDWebImage/GIF'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'Hyphenate', '~> 3.7.1'

end

