platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EMiOSDemo' do

    pod 'Bugly'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'SDWebImage/GIF'
    pod 'FLAnimatedImage', '~> 1.0'

    pod 'Hyphenate'

end
