platform :ios, '9.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EMiOSDemo' do

    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'SDWebImage/GIF'
    pod 'Hyphenate', '~> 3.6.8'
    pod 'FLAnimatedImage', '~> 1.0'

end
